package com.yandex.taskmanagerapp.test;

import com.yandex.taskmanagerapp.model.Epic;
import com.yandex.taskmanagerapp.model.Subtask;
import com.yandex.taskmanagerapp.service.Managers;
import com.yandex.taskmanagerapp.service.TaskManager;
import com.yandex.taskmanagerapp.service.Status;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class EpicTest {
    private final TaskManager tm = Managers.getDefault();

    @Test
    void epicCannotContainItselfInSubtasks() {
        Epic epic = new Epic("Epic", "non description");
        tm.createEpic(epic);
        Subtask subtask1 = new Subtask("first_sub", "non desc", Status.NEW );
        Subtask subtask2 = new Subtask("second_sub", "non desc", Status.NEW );
        ArrayList<Subtask> subtasks = new ArrayList<>();

        subtask2.setId(epic.getId());
        subtask1.setIdEpic(epic.getId());
        subtask2.setIdEpic(epic.getId());
        tm.createSubtask(subtask1);
        tm.createSubtask(subtask2);
        subtasks.add(subtask1);
        subtasks.add(subtask2);
        epic.setSubtasks(subtasks);
        for (Subtask sub : epic.getSubtasks()) {
            assertNotEquals(epic.getId(), sub.getId(), "Epic не должен содержать сам себя");
        }
    }

    @Test
    void equalsToEachOtherIfEqualsId() {
        Epic epic1 = new Epic("first_epic", "non desc");
        Epic epic2 = new Epic("second_epic", "non desc");

        tm.createEpic(epic1);
        tm.createEpic(epic2);
        epic2.setId(1);
        assertEquals(epic1, epic2, "Эпики должны быть равны друг другу так как у них одинаковый id");
    }

    @Test
    void manualAndAutoGeneratedIdsDoNotConflict() {
        Epic epicAuto = new Epic("first_epic", "non desc");
        Epic epicManual = new Epic("second_epic", "non desc");

        tm.createEpic(epicManual);
        epicManual.setId(10);
        assertNotEquals(epicManual.getId(), epicAuto.getId(), "Сгенерированный id не должен совпадать с ручным");
    }

    @Test
    void checkImmutabilityAllFieldsEpics() {
        Epic epic = new Epic("first_epic", "non desc");
        Subtask subtask = new Subtask("first_sub", "non desc", Status.NEW);
        boolean allFieldsEpicsEquals = false;

        tm.createEpic(epic);
        subtask.setIdEpic(epic.getId());
        tm.createSubtask(subtask);
        Epic epicInManager = tm.getEpic(epic.getId());
        if (epic.getId() == epicInManager.getId() && epic.getName().equals(epicInManager.getName())
                && epic.getDescription().equals(epicInManager.getDescription())
                && epic.getStatus() == epicInManager.getStatus()
                && epic.getSubtasks().equals(epicInManager.getSubtasks())) {
            allFieldsEpicsEquals = true;
        }
        assertTrue(allFieldsEpicsEquals, "Поля не должны меняться при добавлении эпика в менеджер");
    }
}