package com.yandex.taskmanagerapp.test;

import com.yandex.taskmanagerapp.model.Epic;
import com.yandex.taskmanagerapp.model.Subtask;
import com.yandex.taskmanagerapp.model.Task;
import com.yandex.taskmanagerapp.service.Managers;
import com.yandex.taskmanagerapp.service.TaskManager;
import com.yandex.taskmanagerapp.service.Status;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

public class SubtaskTest {
    private final TaskManager tm = Managers.getDefault();

    @Test
    void subtaskCannotBeItsOwnEpic() {
        Subtask sub = new Subtask("first_sub", "non desc", Status.NEW );
        assertNotEquals(sub.getId(), sub.getIdEpic(), "Subtask не может ссылаться на себя как на эпик");
    }

    @Test
    void manualAndAutoGeneratedIdsDoNotConflict() {
        Subtask subAuto = new Subtask("first_sub", "non desc", Status.NEW );
        Subtask subManual = new Subtask("second_sub", "non desc", Status.NEW );
        tm.createSubtask(subManual);
        subManual.setId(10);

        assertNotEquals(subManual.getId(), subAuto.getId(), "Сгенерированный id не должен совпадать с ручным");
    }

    @Test
    void equalsToEachOtherIfEqualsId() {
        Subtask sub1 = new Subtask("first_sub", "non desc", Status.NEW );
        Subtask sub2 = new Subtask("second_sub", "non desc", Status.NEW );

        tm.createSubtask(sub1);
        tm.createSubtask(sub2);
        sub2.setId(1);
        assertEquals(sub1, sub2, "Сабтаски должны быть равны друг другу так как у них одинаковый id");
    }
}
