package com.yandex.taskmanagerapp.test;

import com.yandex.taskmanagerapp.model.Epic;
import com.yandex.taskmanagerapp.model.Subtask;
import com.yandex.taskmanagerapp.model.Task;
import com.yandex.taskmanagerapp.service.Managers;
import com.yandex.taskmanagerapp.service.TaskManager;
import com.yandex.taskmanagerapp.service.Status;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

public class TaskTest {
    private final TaskManager tm = Managers.getDefault();

    @Test
    void equalsToEachOtherIfEqualsId() {
        Task task1 = new Task("first_task", "non desc", Status.NEW);
        Task task2 = new Task("second_task", "non desc", Status.NEW);

        tm.createTask(task1);
        tm.createTask(task2);
        task2.setId(1);
        assertEquals(task1, task2, "Таски должны быть равны друг другу так как у них одинаковый id");
    }

    @Test
    void manualAndAutoGeneratedIdsDoNotConflict() {
        Task taskAuto = new Task("first_task", "non desc", Status.NEW);
        Task taskManual = new Task("second_task", "non desc", Status.NEW);
        tm.createTask(taskManual);
        taskManual.setId(10);

        assertNotEquals(taskManual.getId(), taskAuto.getId(), "Сгенерированный id не должен совпадать с ручным");
    }
}
