package com.test;

import com.yandex.taskmanagerapp.model.Subtask;
import com.yandex.taskmanagerapp.service.Managers;
import com.yandex.taskmanagerapp.service.TaskManager;
import com.yandex.taskmanagerapp.enums.Status;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class SubtaskTest {
    private final TaskManager tm = Managers.getMemoryTaskManager();

    @Test
    void subtaskCannotBeItsOwnEpic() {
        Subtask subtask = new Subtask("first_sub", "non desc", Status.NEW, 30,
                "2025-08-01 10:00:00");

        assertNotEquals(subtask.getId(), subtask.getIdEpic(), "Subtask не может ссылаться на себя как на эпик");
    }

    @Test
    void manualAndAutoGeneratedIdsDoNotConflict() {
        Subtask subAuto = new Subtask("first_sub", "non desc", Status.NEW, 30,
                "2025-08-01 10:00:00");
        Subtask subManual = new Subtask("second_sub", "non desc", Status.NEW, 45,
                "2025-08-01 12:00:00");

        tm.addSubtask(subManual);
        subManual.setId(10);
        assertNotEquals(subManual.getId(), subAuto.getId(), "Сгенерированный id не должен совпадать с ручным");
    }

    @Test
    void equalsToEachOtherIfEqualsId() {
        Subtask subtask1 = new Subtask("first_sub", "non desc", Status.NEW, 30,
                "2025-08-01 10:00:00");
        Subtask subtask2 = new Subtask("second_sub", "non desc", Status.NEW, 45,
                "2025-08-01 12:00:00");

        tm.addSubtask(subtask1);
        tm.addSubtask(subtask2);
        subtask2.setId(1);
        assertEquals(subtask1, subtask2, "Сабтаски должны быть равны друг другу так как у них одинаковый id");
    }

    @Test
    void checkImmutabilityAllFieldsSubtasks() {
        Subtask subtask = new Subtask("first_sub", "non desc", Status.NEW, 30,
                "2025-08-01 10:00:00");
        boolean allFieldsSubtasksEquals = false;

        subtask.setIdEpic(1);
        tm.addSubtask(subtask);
        Subtask subtaskInManager = (Subtask) tm.getTask(subtask.getId());
        if (subtask.getId() == subtaskInManager.getId() && subtask.getName().equals(subtaskInManager.getName())
                && subtask.getDescription().equals(subtaskInManager.getDescription())
                && subtask.getStatus() == subtaskInManager.getStatus() && subtask.getIdEpic() == subtaskInManager.getIdEpic()) {
            allFieldsSubtasksEquals = true;
        }
        assertTrue(allFieldsSubtasksEquals, "Поля не должны меняться при добавлении эпика в менеджер");
    }
}