package com.test;

import com.yandex.taskmanagerapp.model.Subtask;
import com.yandex.taskmanagerapp.service.Managers;
import com.yandex.taskmanagerapp.service.TaskManager;
import com.yandex.taskmanagerapp.enums.Status;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class SubtaskTest {
    private final TaskManager tm = Managers.getDefault();

    @Test
    void subtaskCannotBeItsOwnEpic() {
        Subtask subtask = new Subtask("first_sub", "non desc", Status.NEW );

        assertNotEquals(subtask.getId(), subtask.getIdEpic(), "Subtask не может ссылаться на себя как на эпик");
    }

    @Test
    void manualAndAutoGeneratedIdsDoNotConflict() {
        Subtask subAuto = new Subtask("first_sub", "non desc", Status.NEW );
        Subtask subManual = new Subtask("second_sub", "non desc", Status.NEW );

        tm.createSubtask(subManual);
        subManual.setId(10);
        assertNotEquals(subManual.getId(), subAuto.getId(), "Сгенерированный id не должен совпадать с ручным");
    }

    @Test
    void equalsToEachOtherIfEqualsId() {
        Subtask subtask1 = new Subtask("first_sub", "non desc", Status.NEW );
        Subtask subtask2 = new Subtask("second_sub", "non desc", Status.NEW );

        tm.createSubtask(subtask1);
        tm.createSubtask(subtask2);
        subtask2.setId(1);
        assertEquals(subtask1, subtask2, "Сабтаски должны быть равны друг другу так как у них одинаковый id");
    }

    @Test
    void checkImmutabilityAllFieldsSubtasks() {
        Subtask subtask = new Subtask("first_sub", "non desc", Status.NEW );
        boolean allFieldsSubtasksEquals = false;

        subtask.setIdEpic(1);
        tm.createSubtask(subtask);
        Subtask subtaskInManager = tm.getSubtask(subtask.getId());
        if (subtask.getId() == subtaskInManager.getId() && subtask.getName().equals(subtaskInManager.getName())
                && subtask.getDescription().equals(subtaskInManager.getDescription())
                && subtask.getStatus() == subtaskInManager.getStatus() && subtask.getIdEpic() == subtaskInManager.getIdEpic()) {
            allFieldsSubtasksEquals = true;
        }
        assertTrue(allFieldsSubtasksEquals, "Поля не должны меняться при добавлении эпика в менеджер");
    }
}